$! Generated by CONFIGURE.COM - edit DESCRIP.MMS, not this file.
$!
$! SDLLIB - the SDL 1.2 linker options file this system links with.
$! CSTD   - the /STANDARD keyword this compiler accepts for C99
$!          syntax WITH the CRTL POSIX names still visible.
$! VMSINC - empty when this compiler has its own <stdint.h> and
$!          <stdbool.h>; ",[.VMSINC]" when it does not and the
$!          shims there are needed.  Do not set it by hand on a
$!          compiler that has the real headers - /INCLUDE comes
$!          first, so it would shadow them.
$! VMSDEFS- normally empty.  Set only when [.VMSINC] is in use AND
$!          this compiler has no <inttypes.h> to take the 64-bit
$!          types from, in which case the shim declares them itself.
$! All four override the defaults in DESCRIP.MMS, which explains them.
$ SET NOON
$ MMK/IGN=WAR/MACRO=("SDLLIB=LIBSDL:LIBSDL$SHR/OPT","CSTD=/STANDARD=RELAXED","VMSINC=,[.VMSINC]","VMSDEFS=")
