# Generated by ./configure -- edit configure or re-run it, not this file.
CONFIGURED  := yes
CC          := cc
STD         := -std=c99
OPT         := -O2 -g
SAN         := 
SDL_CFLAGS  := -D_THREAD_SAFE -I/usr/local/include -I/usr/local/include/SDL2
SDL_LIBS    := -L/usr/local/lib -lSDL2 -Wl,-rpath,/usr/local/lib
SDL_DEF     := -DCOAB_SDL2=1
SDL_NAME    := SDL2 2.33.0 (pkg-config)
EXTRA_CFLAGS := 
EXTRA_LDFLAGS := 
PREFIX      := /usr/local
EXEC_PREFIX := /usr/local
BINDIR      := /usr/local/bin
DATAROOTDIR := /usr/local/share
GAME_DATA   := 
